# Generated by Django 5.2.16 on 2026-07-17

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.preferences.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai",
                        max_length=64,
                        validators=[apps.preferences.models.validate_iana_timezone],
                    ),
                ),
                ("locale", models.CharField(default="zh-CN", max_length=35)),
                ("workday_start", models.TimeField(default=datetime.time(9, 0))),
                ("workday_end", models.TimeField(default=datetime.time(18, 0))),
                ("sleep_start", models.TimeField(default=datetime.time(23, 0))),
                ("sleep_end", models.TimeField(default=datetime.time(7, 0))),
                ("default_event_duration_minutes", models.PositiveSmallIntegerField(default=60)),
                ("preferred_focus_periods", models.JSONField(blank=True, default=list)),
                ("default_reminder_offsets", models.JSONField(blank=True, default=list)),
                ("weather_location", models.CharField(blank=True, max_length=255)),
                ("news_topics", models.JSONField(blank=True, default=list)),
                ("briefing_time", models.TimeField(default=datetime.time(8, 0))),
                ("planning_rules", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["user_id"]},
        ),
    ]
