# Generated by Django 5.2.16 on 2026-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='weather_forecast_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
