# Generated by Django 5.2.16 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0004_userpreference_require_event_cancellation_approval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="require_event_cancellation_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="require_event_creation_approval",
            field=models.BooleanField(default=False),
        ),
    ]
