# Generated by Django 5.2.16 on 2026-07-16 16:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.preferences.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("calendar_event", "Calendar event"),
                            ("task", "Task"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("trigger_at", models.DateTimeField()),
                (
                    "timezone",
                    models.CharField(
                        max_length=64, validators=[apps.preferences.models.validate_iana_timezone]
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("console", "Console"),
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("browser", "Browser"),
                        ],
                        default="console",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=128)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["trigger_at", "id"],
                "indexes": [
                    models.Index(fields=["status", "trigger_at"], name="reminder_due_scan_idx"),
                    models.Index(fields=["user", "status"], name="reminder_user_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "deduplication_key"),
                        name="reminder_unique_user_deduplication_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_id__isnull", True), ("target_type", "custom")),
                            models.Q(
                                models.Q(("target_type", "custom"), _negated=True),
                                ("target_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="reminder_target_reference_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "sent"), _negated=True),
                            ("sent_at__isnull", False),
                            _connector="OR",
                        ),
                        name="reminder_sent_has_timestamp",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "failed"), _negated=True),
                            models.Q(("failure_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="reminder_failed_has_reason",
                    ),
                ],
            },
        ),
    ]
