# Generated by Django 5.2.16 on 2026-07-23 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="offset_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="schedule_anchor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("task_planned_start", "Task planned start"),
                    ("event_start", "Event start"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("offset_minutes__isnull", True), ("schedule_anchor", "")),
                    models.Q(
                        models.Q(("schedule_anchor", ""), _negated=True),
                        ("offset_minutes__gt", 0),
                        ("offset_minutes__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="reminder_schedule_metadata_consistent",
            ),
        ),
    ]
