# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reminders", "0003_reminder_version")]

    operations = [
        migrations.RemoveConstraint(
            model_name="reminder",
            name="reminder_schedule_metadata_consistent",
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(schedule_anchor="", offset_minutes__isnull=True)
                    | (
                        ~models.Q(schedule_anchor="")
                        & models.Q(offset_minutes__isnull=False, offset_minutes__gte=0)
                    )
                ),
                name="reminder_schedule_metadata_consistent",
            ),
        ),
    ]
