# Generated by Django 5.2.16 on 2026-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0004_allow_exact_start_scheduled_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("missed", "Missed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
