# Generated by Django 5.2.16 on 2026-07-21 09:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reminder_console_enabled", models.BooleanField(default=True)),
                ("reminder_email_enabled", models.BooleanField(default=False)),
                ("reminder_web_push_enabled", models.BooleanField(default=False)),
                ("briefing_console_enabled", models.BooleanField(default=True)),
                ("briefing_email_enabled", models.BooleanField(default=False)),
                ("briefing_web_push_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("briefing", "Briefing"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.UUIDField(blank=True, null=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("console", "Console"),
                            ("email", "Email"),
                            ("web_push", "Web push"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("scheduled_at", models.DateTimeField()),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sending_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"], name="notification_due_scan_idx"
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"], name="notification_retry_scan_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="notification_user_created_idx"
                    ),
                    models.Index(
                        fields=["user", "source_type", "source_id"],
                        name="notification_user_source_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "deduplication_key"),
                        name="notification_unique_user_dedup_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "sent"), _negated=True),
                            ("sent_at__isnull", False),
                            _connector="OR",
                        ),
                        name="notification_sent_has_timestamp",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "failed"), _negated=True),
                            models.Q(
                                ("failed_at__isnull", False),
                                models.Q(("failure_code", ""), _negated=True),
                                models.Q(("failure_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="notification_failed_has_details",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("endpoint", models.URLField(max_length=2048, unique=True)),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("enabled", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(fields=["user", "enabled"], name="webpush_user_enabled_idx")
                ],
            },
        ),
    ]
