# Generated by Django 5.2.16 on 2026-07-21 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "pending"),
                    ("status", "cancelled"),
                    ("queued_at__isnull", False),
                    _connector="OR",
                ),
                name="notification_active_has_queued_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "queued", "cancelled"]),
                    ("sending_at__isnull", False),
                    _connector="OR",
                ),
                name="notification_attempt_has_sending_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_type", "system"), ("source_id__isnull", False), _connector="OR"
                ),
                name="notification_business_source_has_id",
            ),
        ),
    ]
