# Generated by Django 5.2.16 on 2026-07-19 14:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalNewsItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("feed_name", models.CharField(max_length=160)),
                ("feed_url", models.URLField(max_length=1000)),
                ("external_id", models.CharField(max_length=1000)),
                ("canonical_url", models.URLField(max_length=2000)),
                ("title", models.CharField(max_length=1000)),
                ("summary", models.TextField(blank=True)),
                ("publisher", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField()),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("categories", models.JSONField(default=list)),
                ("content_fingerprint", models.CharField(max_length=64, unique=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-id"],
                "indexes": [
                    models.Index(fields=["-published_at"], name="external_news_published_idx"),
                    models.Index(
                        fields=["publisher", "-published_at"], name="external_news_source_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "feed_url", "external_id"),
                        name="external_news_provider_id_uniq",
                    )
                ],
            },
        ),
    ]
