# Generated by Django 5.2.16 on 2026-07-17 05:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.preferences.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "timezone",
                    models.CharField(
                        max_length=64, validators=[apps.preferences.models.validate_iana_timezone]
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tentative", "Tentative"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("recurrence_rule", models.TextField(blank=True)),
                ("source", models.CharField(default="local", max_length=64)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_at", "end_at"], name="calendar_event_user_time_idx"
                    ),
                    models.Index(
                        fields=["user", "status", "start_at"], name="calendar_event_user_status_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="calendar_event_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="calendar_event_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("external_id", ""), ("source", "local")),
                            models.Q(
                                models.Q(("source", "local"), _negated=True),
                                models.Q(("external_id", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="calendar_event_external_identity_consistent",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("user", "source", "external_id"),
                        name="calendar_event_unique_external_identity",
                    ),
                ],
            },
        ),
    ]
