# Generated by Django 5.2.16 on 2026-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0001_llm_call_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcallaudit",
            name="prompt_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
