# Generated by Django 5.2.16 on 2026-07-18 16:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0003_alter_agentrun_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tool_call_id", models.CharField(max_length=255)),
                ("original_request", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("action_type", models.CharField(max_length=128)),
                ("action_payload", models.JSONField(default=dict)),
                ("original_payload", models.JSONField(default=dict)),
                ("display_context", models.JSONField(default=dict)),
                (
                    "risk_level",
                    models.CharField(choices=[("high", "High")], default="high", max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="awaiting_approval",
                        max_length=32,
                    ),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("decision_type", models.CharField(blank=True, max_length=16)),
                ("decision_idempotency_key", models.UUIDField(blank=True, null=True, unique=True)),
                ("execution_result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_proposals",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_proposals",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"], name="proposal_user_status_idx"
                    ),
                    models.Index(
                        fields=["expires_at", "status"], name="proposal_expiry_status_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent_run", "tool_call_id"), name="proposal_run_tool_call_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)), name="proposal_version_positive"
                    ),
                ],
            },
        ),
    ]
