# Generated by Django 5.2.16 on 2026-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_agentrun_execution_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("waiting_approval", "Waiting for approval"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
