# Generated by Django 5.2.16 on 2026-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_alter_agentrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="synthetic_input",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="trigger_payload",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="trigger_type",
            field=models.CharField(default="user_message", max_length=32),
        ),
        migrations.AddField(
            model_name="conversation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("manual_briefing", "Manual briefing"),
                    ("scheduled_briefing", "Scheduled briefing"),
                ],
                default="chat",
                max_length=24,
            ),
        ),
    ]
