# Generated by Django 5.2.16 on 2026-07-19 12:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0004_agentrun_synthetic_input_agentrun_trigger_payload_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BriefingDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("enabled_sections", models.JSONField(default=list)),
                ("locale", models.CharField(blank=True, max_length=32)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("concise", "Concise"),
                            ("balanced", "Balanced"),
                            ("detailed", "Detailed"),
                        ],
                        default="balanced",
                        max_length=16,
                    ),
                ),
                ("include_empty_sections", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefing_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BriefingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_id", models.UUIDField(unique=True)),
                ("trigger_type", models.CharField(max_length=32)),
                ("target_date", models.DateField()),
                ("timezone", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("definition_snapshot", models.JSONField(default=dict)),
                ("structured_result", models.JSONField(default=dict)),
                ("rendered_markdown", models.TextField(blank=True)),
                ("warnings", models.JSONField(default=list)),
                ("model_config_snapshot", models.JSONField(default=dict)),
                ("prompt_version", models.CharField(blank=True, max_length=64)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="briefing_run",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="briefing_runs",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="briefings.briefingdefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefing_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BriefingSectionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("section_key", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("source_snapshot", models.JSONField(default=dict)),
                ("source_references", models.JSONField(default=list)),
                ("warning", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "briefing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_runs",
                        to="briefings.briefingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["section_key"],
            },
        ),
        migrations.AddConstraint(
            model_name="briefingdefinition",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="briefing_definition_user_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="briefingrun",
            index=models.Index(fields=["user", "-created_at"], name="brief_run_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="briefingrun",
            index=models.Index(
                fields=["status", "created_at"], name="brief_run_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="briefingsectionrun",
            constraint=models.UniqueConstraint(
                fields=("briefing_run", "section_key"), name="briefing_section_run_key_uniq"
            ),
        ),
    ]
