# Generated by Django 5.2.16 on 2026-07-17 05:28

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("project", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("planned_start_at", models.DateTimeField(blank=True, null=True)),
                ("planned_end_at", models.DateTimeField(blank=True, null=True)),
                ("actual_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="local", max_length=64)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_at", "created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "due_at"], name="task_user_status_due_idx"
                    ),
                    models.Index(fields=["user", "planned_start_at"], name="task_user_planned_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("planned_end_at__isnull", True), ("planned_start_at__isnull", True)
                            ),
                            models.Q(
                                ("planned_start_at__isnull", False),
                                ("planned_end_at__isnull", False),
                                ("planned_end_at__gt", models.F("planned_start_at")),
                            ),
                            _connector="OR",
                        ),
                        name="task_planned_range_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estimated_minutes__isnull", True),
                            ("estimated_minutes__gte", 1),
                            _connector="OR",
                        ),
                        name="task_estimated_minutes_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("completed_at__isnull", False), ("status", "completed")),
                            models.Q(
                                models.Q(("status", "completed"), _negated=True),
                                ("completed_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="task_completed_timestamp_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "in_progress"), _negated=True),
                            ("actual_started_at__isnull", False),
                            _connector="OR",
                        ),
                        name="task_in_progress_has_start",
                    ),
                ],
            },
        ),
    ]
