# Generated by Django 5.2.16 on 2026-08-24 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_taskexecutionsignal"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="buffer_after_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1440)]
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="buffer_before_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1440)]
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="planning_locked",
            field=models.BooleanField(default=False),
        ),
    ]
