# Generated by Django 5.2.16 on 2026-08-24 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_buffer_after_minutes_task_buffer_before_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="minimum_chunk_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(1440),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="splittable",
            field=models.BooleanField(default=False),
        ),
    ]
