# Generated by Django 5.2.16 on 2026-10-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_minimum_chunk_minutes_task_splittable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecutionsignal',
            name='signal_type',
            field=models.CharField(choices=[('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('skipped', 'Skipped')], max_length=16),
        ),
    ]
