# Generated by Django 5.2.16 on 2026-10-01 17:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.interactions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0005_agentrun_anchor"),
        ("planning", "0006_automationpolicy_authorized_task_ids"),
        ("tasks", "0005_task_minimum_chunk_minutes_task_splittable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("plan_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("priority_ranking", "Priority ranking"),
                            ("plan_timeline_edit", "Plan timeline edit"),
                            ("task_completion", "Task completion feedback"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("allowed_actions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.interactions.models.default_interaction_expiry
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conversations.conversation",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.scheduleplan",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InteractionSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("expected_version", models.PositiveIntegerField()),
                ("action", models.CharField(max_length=32)),
                ("values", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="interactions.interactionartifact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="InteractionTelemetryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("interaction_shown", "Interaction shown"),
                            ("interaction_started", "Interaction started"),
                            ("interaction_completed", "Interaction completed"),
                            ("interaction_abandoned", "Interaction abandoned"),
                            (
                                "plan_acceptance_after_interaction",
                                "Plan accepted after interaction",
                            ),
                            ("memory_suggestion_shown", "Memory suggestion shown"),
                            ("memory_suggestion_accepted", "Memory suggestion accepted"),
                            ("day_close_completion_rate", "Day close completed"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("priority_ranking", "Priority ranking"),
                            ("plan_timeline_edit", "Plan timeline edit"),
                            ("task_completion", "Task completion feedback"),
                        ],
                        max_length=32,
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("drag_count", models.PositiveSmallIntegerField(default=0)),
                ("invalid_drop_count", models.PositiveSmallIntegerField(default=0)),
                ("undo_count", models.PositiveSmallIntegerField(default=0)),
                ("plan_edit_count", models.PositiveSmallIntegerField(default=0)),
                ("actual_vs_planned_ratio", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="interaction_event_time_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="interactionartifact",
            index=models.Index(
                fields=["user", "status", "expires_at"], name="inter_user_status_exp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionartifact",
            index=models.Index(fields=["plan", "status"], name="interaction_plan_status_idx"),
        ),
        migrations.AddIndex(
            model_name="interactionartifact",
            index=models.Index(fields=["task", "status"], name="interaction_task_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="interactionartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("plan__isnull", False),
                        ("type__in", ["priority_ranking", "plan_timeline_edit"]),
                    ),
                    models.Q(("task__isnull", False), ("type", "task_completion")),
                    _connector="OR",
                ),
                name="inter_target_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionsubmission",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="inter_user_idem_uniq"
            ),
        ),
    ]
