# Generated by Django 5.2.16 on 2026-10-01 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_agentrun_anchor"),
        ("interactions", "0001_initial"),
        ("planning", "0006_automationpolicy_authorized_task_ids"),
        ("tasks", "0005_task_minimum_chunk_minutes_task_splittable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="interactionartifact",
            name="inter_target_type_ck",
        ),
        migrations.AlterField(
            model_name="interactionartifact",
            name="type",
            field=models.CharField(
                choices=[
                    ("priority_ranking", "Priority ranking"),
                    ("plan_timeline_edit", "Plan timeline edit"),
                    ("task_completion", "Task completion feedback"),
                    ("memory_suggestion", "Memory suggestion"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="interactiontelemetryevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("interaction_shown", "Interaction shown"),
                    ("interaction_started", "Interaction started"),
                    ("interaction_completed", "Interaction completed"),
                    ("interaction_abandoned", "Interaction abandoned"),
                    ("completion_feedback_rate", "Completion feedback rate"),
                    ("plan_acceptance_after_interaction", "Plan accepted after interaction"),
                    ("memory_suggestion_shown", "Memory suggestion shown"),
                    ("memory_suggestion_accepted", "Memory suggestion accepted"),
                    ("day_close_completion_rate", "Day close completed"),
                    ("invalid_drop", "Invalid drop"),
                    ("plan_edit", "Plan edit"),
                    ("undo", "Undo"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="interactiontelemetryevent",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("priority_ranking", "Priority ranking"),
                    ("plan_timeline_edit", "Plan timeline edit"),
                    ("task_completion", "Task completion feedback"),
                    ("memory_suggestion", "Memory suggestion"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("plan__isnull", False),
                        ("type__in", ["priority_ranking", "plan_timeline_edit"]),
                    ),
                    models.Q(
                        ("task__isnull", False),
                        ("type__in", ["task_completion", "memory_suggestion"]),
                    ),
                    _connector="OR",
                ),
                name="inter_target_type_ck",
            ),
        ),
    ]
