# Generated by Django 5.2.16 on 2026-10-01 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_agentrun_anchor"),
        ("interactions", "0002_remove_interactionartifact_inter_target_type_ck_and_more"),
        ("planning", "0006_automationpolicy_authorized_task_ids"),
        ("tasks", "0005_task_minimum_chunk_minutes_task_splittable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="interactionartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plan__isnull", False), ("status", "pending")),
                fields=("user", "type", "plan"),
                name="inter_user_type_plan_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending"), ("task__isnull", False)),
                fields=("user", "type", "task"),
                name="inter_user_type_task_pending",
            ),
        ),
    ]
