# Generated by Django 5.2.16 on 2026-10-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_interactionartifact_inter_user_type_plan_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactionartifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                    ("expired", "Expired"),
                    ("stale", "Stale"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
