# Generated by Django 5.2.16 on 2026-10-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_interactionartifact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionsubmission',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
