# Generated by Django 5.2.16 on 2026-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("time_memory", "0002_exclusions_and_reset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulechange",
            name="entity_type",
            field=models.CharField(
                choices=[("event", "Event"), ("task", "Task"), ("reminder", "Reminder")],
                max_length=16,
            ),
        ),
    ]
