# Generated by Django 5.2.16 on 2026-08-30 16:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_agentrun_anchor"),
        ("time_memory", "0005_alter_timedecisionfeedback_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("ignore", "Ignore"),
                        ],
                        max_length=16,
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=128)),
                ("value", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence_hash", models.CharField(blank=True, max_length=64)),
                ("reason_code", models.CharField(max_length=64)),
                ("policy_reason", models.CharField(blank=True, max_length=128)),
                ("model_alias", models.CharField(blank=True, max_length=64)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("idempotency_key", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_proposals",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"], name="memory_proposal_status_idx"
                    ),
                    models.Index(
                        fields=["user", "category", "key"], name="memory_proposal_target_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "idempotency_key"), name="memory_proposal_user_key_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SemanticMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=128)),
                ("value", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("explicit_user", "Explicit user"),
                            ("background_extraction", "Background extraction"),
                            ("user_edit", "User edit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence_hash", models.CharField(blank=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="semantic_memories",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status", "category"], name="semantic_memory_lookup_idx"
                    ),
                    models.Index(fields=["user", "expires_at"], name="semantic_memory_expiry_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("user", "category", "key"),
                        name="semantic_memory_active_uniq",
                    )
                ],
            },
        ),
    ]
