# Generated by Django 5.2.16 on 2026-08-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("time_memory", "0006_memoryproposal_semanticmemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryproposal",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("background_extraction", "Background extraction"),
                    ("agent_tool", "Agent tool"),
                ],
                default="background_extraction",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="memoryproposal",
            name="target_memory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_proposals",
                to="time_memory.semanticmemory",
            ),
        ),
        migrations.AddField(
            model_name="memoryproposal",
            name="target_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="memoryproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("applied", "Applied"),
                    ("expired", "Expired"),
                    ("conflicted", "Conflicted"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
