# Generated by Django 5.2.16 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("time_memory", "0007_memoryproposal_source_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryproposal",
            name="applied_memory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_proposals",
                to="time_memory.semanticmemory",
            ),
        ),
        migrations.AddField(
            model_name="memoryproposal",
            name="applied_memory_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memoryproposal",
            name="changed_business_state",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memoryproposal",
            name="undone_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="memoryproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("applied", "Applied"),
                    ("expired", "Expired"),
                    ("conflicted", "Conflicted"),
                    ("undone", "Undone"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
