# Generated by Django 5.2.16 on 2026-08-24 09:08

from django.db import migrations, models

import apps.planning.models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0004_schedulechangebatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleplan",
            name="abandoned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="constraints_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="decision_profile_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="expires_at",
            field=models.DateTimeField(default=apps.planning.models.default_schedule_plan_expiry),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="invalidation_reason",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="scheduleplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("applied", "Applied"),
                    ("superseded", "Superseded"),
                    ("abandoned", "Abandoned"),
                    ("invalidated", "Invalidated"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
