# Generated by Django 5.2.16 on 2026-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0005_scheduleplan_abandoned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationpolicy",
            name="authorized_task_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
