# Generated by Django 5.2.16 on 2026-10-03 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0006_automationpolicy_authorized_task_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleplan",
            name="operation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="scheduleplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("operation_id__isnull", False)),
                fields=("user", "operation_id"),
                name="schedule_plan_user_operation_uniq",
            ),
        ),
    ]
